services:
  payload:
    build: .
    ports:
      - '5252:3000'
    volumes:
      - ./media:/app/media
      - db-data:/app/db
    env_file:
      - .env
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    volumes:
      - /home/smvservadmin/cloudflared-config:/home/nonroot/.cloudflared
    depends_on:
      - payload
    restart: unless-stopped

volumes:
  db-data:
